### ISSUE TITLE
Newly created exercise should show up at top of list

### ISSUE THREAD

**Issue by pambsoftware** [pambsoftware/beefcake#8]
If the exercise does not exist and I create a new one, it's added at end of list. It would be clearer if it should up at top of list. 

Reported by: https://plus.google.com/+StephanWindmüller

**Comment by windmueller** [comment]
In RC1 it appears not on the top of the list, but correctly sorted. This is better, so this bug may be closed.

**Comment by pambsoftware** [comment]
In 5.0.1 it ends up at top of list. Are you sure? Android version? We're inserting it at the top of the list so it would be surprising if it's not there. I know you liked the sorting even better but I'm curious.

Steps I took from Workout Log screen (for a workout log already having 3 exercises): 
1. Press +
2. Press Create Exercise
3. Type a name
4. Save
5. The new exercise shows as item1 in list (even though it starts on S and other on A, B, C)

**Comment by windmueller** [comment]
Sorry, I used the wrong activity. Performing the steps you mentioned works perfectly.
